// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiPondConstruct.Data.Entities;

public partial class TblDesign
{
    public long Id { get; set; }

    public long RequestDetailId { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime UpdatedTime { get; set; }

    public string CreatedBy { get; set; }

    public string File { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime ApprovedTime { get; set; }

    public string ContentText { get; set; }

    public bool IsDeleted { get; set; }

    public virtual TblCustomerRequestDetail RequestDetail { get; set; }

    public virtual TblInspection TblInspection { get; set; }

    public virtual ICollection<TblStatus> TblStatuses { get; set; } = new List<TblStatus>();
}