// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace KoiPondConstruct.Data.Entities;

public partial class TblPriceContractCost
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }

    public long QuotationCostId { get; set; }

    public long PriceReferId { get; set; }

    public int Count { get; set; }

    public long Total { get; set; }

    public bool IsDeleted { get; set; }

    public virtual TblPriceRefer PriceRefer { get; set; }

    public virtual TblQuotationCost QuotationCost { get; set; }
}