// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiPondConstruct.Data.Entities;

public partial class TblSampleDesignImgRefer
{
    public long Id { get; set; }

    public bool IsDeleted { get; set; }

    public long SampleDesignId { get; set; }

    public long ImgReferId { get; set; }

    public virtual TblImgRefer ImgRefer { get; set; }

    public virtual TblSampleDesign SampleDesign { get; set; }
}