// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiPondConstruction.Data.Models;

public partial class TblInspectionDetail
{
    public long Id { get; set; }

    public long InspectionId { get; set; }

    public string Attribute { get; set; }

    public string ObservedValue { get; set; }

    public string ExpectedValue { get; set; }

    public string Result { get; set; }

    public string Comments { get; set; }

    public string Severity { get; set; }

    public virtual TblInspection Inspection { get; set; }
}