// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiPondConstruction.Data.Models;

public partial class TblPriceRefer
{
    public long Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int Price { get; set; }

    public string Currency { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime UpdatedTime { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string Type { get; set; }

    public long Size { get; set; }

    public string SizeUnit { get; set; }

    public virtual ICollection<TblPriceContractCost> TblPriceContractCosts { get; set; } = new List<TblPriceContractCost>();
}