// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiPondConstruction.Data.Models;

public partial class TblRequestDetailSampleDesign
{
    public long Id { get; set; }

    public bool IsDeleted { get; set; }

    public long SampleDesignId { get; set; }

    public long RequestDetailId { get; set; }

    public virtual TblCustomerRequestDetail RequestDetail { get; set; }

    public virtual TblSampleDesign SampleDesign { get; set; }
}