// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiPondConstruction.Data.Models;

public partial class TblSampleDesign
{
    public long Id { get; set; }

    public long ImgId { get; set; }

    public DateTime CreatedTime { get; set; }

    public DateTime UpdatedTime { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime ApprovedTime { get; set; }

    public string Note { get; set; }

    public string File { get; set; }

    public string ContentText { get; set; }

    public bool IsDeleted { get; set; }

    public virtual TblImgRefer Img { get; set; }

    public virtual ICollection<TblRequestDetailSampleDesign> TblRequestDetailSampleDesigns { get; set; } = new List<TblRequestDetailSampleDesign>();

    public virtual ICollection<TblSuggestionDoc> TblSuggestionDocs { get; set; } = new List<TblSuggestionDoc>();
}